services:
  db:
    image: mysql:8.0
    container_name: mysql_database
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: ******
      MYSQL_DATABASE: ***
      MYSQL_ROOT_PASSWORD: ****

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wd-front
    volumes:
      - wd_files:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: ****
      WORDPRESS_DB_NAME: ****

volumes:
  wd_files:
  db_data:

